name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up alire
      uses: alire-project/setup-alire@v1

    - name: Build gnatdoc
      run: >
        alr get gnatdoc &&
        cd gnatdoc* &&
        alr -n update &&
        alr -n build --release
      
    - name: Compress gnatdoc
      run: >
        cd gnatdoc* &&
        tar -cf gnatdoc-linux.tar bin &&
        mv gnatdoc-linux.tar ../
    
    - name: Upload gnatdoc
      uses: actions/upload-artifact@v2
      with:
         name: gnatdoc-linux.tar
         path: gnatdoc-linux.tar


#  build-windows:
#    runs-on: windows-latest
#    
#    steps: 
#    
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up alire
#        uses: alire-project/setup-alire@v1
#
#      - name: Build gnatdoc
#        run: >
#         alr get gnatdoc &&
#         cd gnatdoc* &&
#         alr -n update &&
#         alr -n build --release
#      
#      - name: Compress getada
#        run: 7z a -tzip gnatdoc-win.zip bin
#
#      - name: Upload gnatdoc
#        uses: actions/upload-artifact@v2
#        with:
#         name: gnatdoc-win.zip
#         path: gnatdoc-win.zip
